
openapi: 3.0.0
info:
  title: User Service API
  version: 1.0.0
paths:
  /users/{email}:
    get:
      summary: Get user by email
      parameters:
        - name: email
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A user object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDto'
components:
  schemas:
    UserDto:
      type: object
      properties:
        email:
          type: string
        birthDate:
          type: string
          format: date
        firstName:
          type: string
        lastName:
          type: string